# Movement
move_up = "W"
move_down = "S"
move_left = "A"
move_right = "D"
jump = "Space"
sprint = "ShiftLeft"

# Interaction
interact = "E"
drop_item = "Q"
attack = "MouseLeft"
toggle_game_mode = "F2"
ui_menu = "Escape"
ui_inventory = "Tab"

# Ui
ui_close_back = "Escape"
open_chat = "C"
inventory_recipe_open = "R"

# Debug
debug_overlay = "F3"
chunk_grid = "F9"
world_inspector = "F1"
