mouse_sensitivity_vertical = 1.0
mouse_sensitivity_horizontal = 1.0
mouse_zoom_in = 3.5
mouse_zoom_out = 10.0
mouse_screen_unlock = "Escape"
move_up = "W"
move_down = "S"
move_left = "A"
move_right = "D"
jump = "Space"
sprint = "ShiftLeft"
interact = "E"
drop_item = "Q"
attack = "MouseLeft"
toggle_game_mode = "F2"
ui_menu = "Escape"
ui_inventory = "Tab"
ui_close_back = "Escape"
debug_overlay = "F3"
chunk_grid = "F9"
world_inspector = "F1"
