# Movement
move_up = "W"
move_down = "S"
move_left = "A"
move_right = "D"
jump = "Space"
sprint = "ShiftLeft"

# Interaction
interact = "E"
drop_item = "Q"
attack = "MouseLeft"
toggle_game_mode = "F2"
ui_menu = "Escape"
ui_inventory = "Tab"

# Ui
ui_close_back = "Escape"
open_chat = "C"
inventory_recipe_open = "R"
hotbar_slot_1 = "1"
hotbar_slot_2 = "2"
hotbar_slot_3 = "3"
hotbar_slot_4 = "4"
hotbar_slot_5 = "5"
hotbar_slot_6 = "6"

# Debug
debug_overlay = "F3"
collider_debug = "F8"
chunk_grid = "F9"
world_inspector = "F1"
